#!/usr/bin/env bash
# ping 5 times (ping an IP address passed as an argument and displays 'Usage: 5-is_the_host_on_the_network {IP_ADDRESS}' if no argument is passed)

if [ $# -eq 1 ] 
	then 
		ping -c 5 "${1}"

else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
